services:

  rabbitmq:
    image: "rabbitmq:4-management"
    container_name: rabbitmq_ctn
    ports:
      - 5672:5672 # standard port
      - 7005:15672 # web ui (customized)
    networks:
      - backend_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=eva
      - RABBITMQ_DEFAULT_PASS=eva123

  postgres:
    image: "postgres:17-alpine"
    container_name: postgres_ctn
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=psql123
      - POSTGRES_USER:eva
      - POSTGRES_DB=evadb_catalog

networks:
  backend_network:

volumes:
  rabbitmq_data:
  rabbitmq_logs:
  mongodb_data:
  postgres_data: